# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_all

datas = [('assets', 'assets')]
binaries = []
hiddenimports = [
    'gdrive_sync',
    'gdrive_sync.auth',
    'gdrive_sync.auth.oauth',
    'gdrive_sync.auth.token_storage',
    'gdrive_sync.config',
    'gdrive_sync.database',
    'gdrive_sync.database.manager',
    'gdrive_sync.database.models',
    'gdrive_sync.database.schema',
    'gdrive_sync.drive',
    'gdrive_sync.drive.client',
    'gdrive_sync.engine',
    'gdrive_sync.engine.poller',
    'gdrive_sync.engine.queue',
    'gdrive_sync.engine.reconciler',
    'gdrive_sync.engine.sync_service',
    'gdrive_sync.engine.utils',
    'gdrive_sync.engine.watcher',
    'gdrive_sync.integrations',
    'gdrive_sync.integrations.autostart',
    'gdrive_sync.ui',
    'gdrive_sync.ui.activity_dialog',
    'gdrive_sync.ui.icons',
    'gdrive_sync.ui.preferences_dialog',
    'gdrive_sync.ui.selective_sync_dialog',
    'gdrive_sync.ui.tray',
    'watchdog',
    'keyring',
    'keyring.backends',
    'keyring.backends.Windows',
    'googleapiclient',
    'googleapiclient.discovery',
    'googleapiclient.http',
    'google_auth_oauthlib',
    'google.auth.transport.requests',
]

excludes = [
    'tkinter',
    'unittest',
    'pytest',
    'PySide6.QtWebEngineCore',
    'PySide6.QtWebEngineWidgets',
    'PySide6.QtWebEngineQuick',
    'PySide6.QtQml',
    'PySide6.QtQuick',
    'PySide6.QtQuickWidgets',
    'PySide6.Qt3DCore',
    'PySide6.Qt3DRender',
    'PySide6.Qt3DInput',
    'PySide6.Qt3DAnimation',
    'PySide6.Qt3DExtras',
    'PySide6.QtDesigner',
    'PySide6.QtMultimedia',
    'PySide6.QtMultimediaWidgets',
    'PySide6.QtSpatialAudio',
    'PySide6.QtSensors',
    'PySide6.QtPositioning',
    'PySide6.QtBluetooth',
    'PySide6.QtNfc',
    'PySide6.QtPdf',
    'PySide6.QtPdfWidgets',
    'PySide6.QtCharts',
    'PySide6.QtDataVisualization',
    'PySide6.QtTest',
]

a = Analysis(
    ['run.py'],
    pathex=['.'],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=1,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='MyGDriveSync',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/gdrive-sync.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='MyGDriveSync',
)
